# Generated by Django 4.2 on 2024-12-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_addition_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
