# Generated by Django 4.2 on 2024-12-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
