# Generated by Django 4.2 on 2024-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_testimonial_icon_alter_testimonial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
